---
title: "hw2-nderon"
output: html_document
---
#Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
library(sp)
library(sf)
library(rgdal)
```

#Data prep
```{r prep}
blotter <- read.csv("Blotter_Data_Archive.csv") #Read blotter data
blotter$INCIDENTTIME <- strptime(x = as.character(blotter$INCIDENTTIME), #Convert INCIDENTTIME to datetime
                                      format = "%Y-%m-%dT%H:%M:%S")
blotter$type <- cut(blotter$HIERARCHY, c(-Inf, 9, 98, Inf), labels = c("Type 1 - Major Crime", "Type 2 - Minor Crime", "No Data or None")) #Convert hierarchy to bucketed factors
blotter_subset <- blotter[blotter$INCIDENTTIME >= "2018-01-01" & blotter$INCIDENTTIME <= "2018-12-31" & blotter$X <= -78 & blotter$Y >= 39 & !is.na(blotter$type),]
blotter_subset <- blotter_subset[sample(1:nrow(blotter_subset), 25),]
historic <- readOGR("City_Designated_Historic_Districts.geojson.json") #read historic district dat
cc_districts <- readOGR("City_Council_Districts.geojson") #read city council district data
```

#Map
```{r map}
#getColor and icons adapted from https://rstudio.github.io/leaflet/markers.html
getColor <- function(data) {
  sapply(data$type, function(type) {
  if(type == "Type 1 - Major Crime") {
    "red"
  } else if(type == "Type 2 - Minor Crime") {
    "orange"
  } else {
    "grey"
  } })
}

icons <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = getColor(blotter_subset)
)

leaflet() %>%
  addTiles(group = "OSM (default)") %>% #default basemap
  addProviderTiles(providers$CartoDB.Positron, group = "Positron") %>% #extra basemaps
  addProviderTiles(providers$Stamen.Toner, group = "Toner") %>%
  addAwesomeMarkers(lng = blotter_subset$X, lat = blotter_subset$Y, icon = icons) %>% #markers
  setView(lng = -79.9959, lat = 40.4406, zoom = 12) %>% #default view
  addLegend(values = blotter_subset$type, colors = c("red", "orange", "grey"), labels = levels(blotter_subset$type)) %>% #lengend
  addPolygons(data = historic, color = "red", fillColor = "#495D4E", opacity = 1, weight = 1, fillOpacity = 0.5, group = "Historic Districts") %>% #historic district polygons
  addPolylines(data = cc_districts, opacity = 1, weight = 1, group = "City Council") %>% #city council district polylines
  addLayersControl(
    baseGroups = c("OSM (default)", "Positron", "Toner"),
    overlayGroups = c("Historic Districts", "City Council"),
    options = layersControlOptions(collapsed = FALSE)
  )
```